---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks.git
  rev: v4.2.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-executables-have-shebangs
- repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt.git
  rev: 0.2.1
  hooks:
  - id: yamlfmt
    args: [--mapping, '2', --sequence, '2', --offset, '0', --width, '150', --preserve-quotes]
- repo: https://github.com/antonbabenko/pre-commit-terraform.git
  rev: v1.50.0
  hooks:
  - id: terraform_fmt
    exclude: \.terraform\/.*$
  - id: terraform_validate
    args: ['--envs=AWS_DEFAULT_REGION="eu-west-1']
  - id: terraform_tflint
    args:
    - --args=--enable-rule=terraform_documented_variables
- repo: https://github.com/terraform-docs/terraform-docs.git
  rev: "v0.16.0"
  hooks:
  - id: terraform-docs-go
    args: ["markdown", "table", "--output-file", "README.md", ".", "--lockfile=false"]
